#!/usr/bin/env python3
"""ingest_measurements.py — turn a MEASUREMENT_RECORD_SHEET.csv into a
reviewable patch against w17_params.scad.

=======================================================================
 CONVENTION THIS TOOL DEPENDS ON (read this before filling in a sheet)
=======================================================================
w17_params.scad tags every shared dimension with a provenance comment.
This tool retires exactly one class of those tags: lines whose comment
is, verbatim, "ASSUMED (see §9)" — the ones §9 lists under the owner's
name and a measurement (M-nn) or coupon (C-1) that retires them. It
does NOT touch "ASSUMED-adjacent" (screw_m3_clear_d), ESTIMATED,
POLICY, DERIVED, DOCUMENTED lines, or the deliberately-undef
drs_arm_pivot_span — those are out of scope by construction, not by
guesswork: the regex only matches the literal "ASSUMED (see §9)" tag.

The CSV schema, as generated by ../../tools/gen_measurement_sheet.py:

    id,param,quantity,unit,value,tolerance,photo_ref,notes

    id          the sheet's row id (e.g. M-03c, M-01.worst, C-1.1).
                Carried into the patch as provenance; never parsed for
                meaning.
    param       THE MAPPING. The bare w17_params.scad parameter name
                this one cell sets (e.g. "esp_thk_headers"), or EMPTY
                for a register-only row — a number the sitting records
                but that must NOT be written into w17_params.scad.
                Register-only is the normal case for a measured STOCK
                dimension whose parameter is a FEATURE the stock has to
                fit through (a screw's thread OD vs screw_m3_clear_d,
                an insert's knurl OD vs the bore it melts into, a cable
                tie's strap vs the slot): feature = stock + clearance,
                which is a CAD decision, not a transcription.
                ONE ROW PER PARAMETER. A quantity read at several
                stations gets N register-only cells plus one derived
                cell that carries the param (M-01.worst, M-02a.min);
                two rows targeting one parameter are a CONFLICT and
                both are skipped.
    quantity    free-text description of what to measure. When the
                sheet HAS a `param` column, this is prose and is never
                parsed for a parameter name. LEGACY FALLBACK: a sheet
                with no `param` column falls back to the pre-2026-09-05
                convention in which `quantity` had to BE the bare
                parameter name; prose quantities then simply MISS.
                Nothing is ever applied on a guessed mapping, and a
                sheet that reads rows and matches nothing exits 1.
    unit        mm (default assumed if blank) or g or deg. "enum" for
                the two string-valued params (esp_usb_type,
                esp_usb_edge) — value is then the literal string
                without quotes (e.g. usb_c).
    value       the measured number, or the literal for an enum row.
                A row whose value is empty, or whose value or notes
                BEGIN with "could not" (the measurement prompt's own
                convention for an untakeable measurement), is skipped
                and reported, never coerced into a number. The test is
                anchored at the start on purpose: several sheet rows
                quote the phrase inside instruction text.
    tolerance   carried into the patch comment; not otherwise used.
    photo_ref   carried into the patch comment when present.
    notes       carried into the patch comment when present.

=======================================================================
 WHAT THE PATCH DOES AND DOES NOT TOUCH
=======================================================================
For every CSV row whose `param` (or, on a legacy sheet, `quantity`)
matches a live "ASSUMED (see §9)" parameter in w17_params.scad, this
tool rewrites ONLY that parameter's
own definition line: the value, and the tag from "ASSUMED (see §9)" to
"MEASURED(<sheet>#<id>, <date>)", keeping whatever descriptive text
followed the old tag (e.g. "brand-dependent") so the rationale is not
lost, and appending tolerance/photo_ref/notes when the CSV supplied
them.

It deliberately does NOT touch section 9's own ASSUMED table, the AA
study's §12, or the measurement-session prompt — the repo's own
editing rule (11_cad/README.md "Editing rules") says a landed
measurement updates three places, and some §9 rows bundle several
parameters under one M-nn (e.g. M-03 lists six). Auto-editing a
bundled row on a partial match risks deleting the record of params
that are still ASSUMED. The patch report instead PRINTS which §9
rows are now fully retired (every parameter they list has a matching
MEASURED line) so a human can strike them in the same commit, and
which are partially retired.

It also prints a RECOMPUTE line for every DERIVED/ESTIMATED parameter
whose own provenance comment names a parameter this run just changed
(e.g. guide_top_margin = 2.0; // DERIVED(board_top_z - guide_top_z)).
Those are hardcoded literals that no assert re-derives, so patching an
input silently desynchronises them. The tool refuses to guess the
arithmetic and instead names them for a human to recompute in the same
commit.

=======================================================================
 USAGE
=======================================================================
    ingest_measurements.py --sheet MEASUREMENT_RECORD_SHEET.csv
        Dry run (the default). Prints a unified diff against
        w17_params.scad and a summary: matched / unmatched CSV rows,
        §9 rows fully vs. partially retired. Writes nothing.

    ingest_measurements.py --sheet SHEET.csv --apply
        Writes the patched w17_params.scad in place, then re-renders
        (./render.sh --stl by default; --skip-render to suppress) and
        reports PASS/FAIL. On any assert() failure or non-clean
        render, the tool still leaves the patched file in place (it is
        a normal, reviewable git diff at that point) but exits
        non-zero and says so plainly — it does not revert your worktree.

    ingest_measurements.py --sheet SHEET.csv --params /other/w17_params.scad
        Patch a different copy (mainly for the test suite).

Exit codes: 0 clean (dry run with no errors, or --apply that rendered
clean); 1 CSV or matching problem — INCLUDING "rows were read and none
of them matched", which is what a sheet/tool column mismatch looks like
and which used to exit 0; 2 --apply rendered dirty.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

REQUIRED_HEADERS = ["id", "quantity", "unit", "value", "tolerance", "photo_ref", "notes"]
# The full, current schema. "param" is optional so a pre-2026-09-05 sheet still
# loads (and then exits 1 on the "nothing matched" check rather than silently
# reporting success), but every sheet the generator writes carries it.
FULL_HEADERS = ["id", "param", "quantity", "unit", "value", "tolerance", "photo_ref", "notes"]

# Matches exactly the "ASSUMED (see §9)" tag this tool is scoped to.
# Captures: name, the "name<ws>=<ws>" prefix, the current value token,
# the ";" plus trailing whitespace before the comment, and whatever
# descriptive text follows the tag on the same line.
ASSUMED_RE = re.compile(
    r"^(?P<prefix>(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?P<sp1>[ \t]+)=(?P<sp2>[ \t]+))"
    r"(?P<value>[^;]+?)"
    r"(?P<mid>;(?P<sp3>[ \t]+)//[ \t]*)"
    r"ASSUMED \(see §9\)"
    r"(?P<rest>.*)$"
)

# A §9 table row, e.g. "//  M-03  esp_thk_headers                                13.0"
# Params are whitespace/slash separated identifiers on the row.
SECTION9_ROW_RE = re.compile(r"^//\s+(?P<mid>[A-Za-z0-9\-\(\)]+)\s+(?P<rest>.*)$")
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# A hardcoded literal whose provenance comment states the inputs it was derived
# from, e.g. "guide_top_margin  = 2.0;    // DERIVED(board_top_z - guide_top_z)".
# Nothing in the file re-derives these, so patching an input desynchronises them.
DERIVED_RE = re.compile(
    r"^(?P<name>[A-Za-z_][A-Za-z0-9_]*)[ \t]+=[ \t]*[^;]+;[ \t]*//[ \t]*"
    r"(?P<tag>DERIVED|ESTIMATED)\((?P<basis>[^)]*)\)"
)


class Row:
    __slots__ = ("id", "param", "quantity", "unit", "value", "tolerance",
                 "photo_ref", "notes", "lineno", "has_param_col")

    def __init__(self, d: dict, lineno: int, has_param_col: bool = False):
        self.id = (d.get("id") or "").strip()
        self.param = (d.get("param") or "").strip()
        self.has_param_col = has_param_col
        self.quantity = (d.get("quantity") or "").strip()
        self.unit = (d.get("unit") or "").strip()
        self.value = (d.get("value") or "").strip()
        self.tolerance = (d.get("tolerance") or "").strip()
        self.photo_ref = (d.get("photo_ref") or "").strip()
        self.notes = (d.get("notes") or "").strip()
        self.lineno = lineno

    def target(self) -> str:
        """The parameter name this row claims to set, or "" for a
        register-only row.

        `param` first: when the sheet has the column, it IS the mapping and
        `quantity` is prose that is never mined for a parameter name. Only a
        legacy sheet (no `param` column) falls back to `quantity`, which the
        pre-2026-09-05 convention required to be the bare parameter name."""
        return self.param if self.has_param_col else self.quantity


def load_sheet(path: Path) -> list[Row]:
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError(f"{path}: empty CSV (no header row)")
        missing = [h for h in REQUIRED_HEADERS if h not in reader.fieldnames]
        if missing:
            raise ValueError(
                f"{path}: missing required column(s) {missing}; "
                f"header row was {reader.fieldnames}"
            )
        has_param_col = "param" in reader.fieldnames
        rows = []
        for i, d in enumerate(reader, start=2):  # header is line 1
            rows.append(Row(d, i, has_param_col))
        return rows


def find_assumed_params(scad_lines: list[str]) -> dict[str, tuple[int, re.Match]]:
    """name -> (0-based line index, regex Match) for every live ASSUMED
    (see §9) definition line. Only matches definitions (before the §9
    table itself), never the §9 table's own commented rows, because
    ASSUMED_RE requires an executable "name = value;" prefix that a
    "//" comment line can never produce."""
    found: dict[str, tuple[int, re.Match]] = {}
    for i, line in enumerate(scad_lines):
        m = ASSUMED_RE.match(line)
        if m:
            found[m.group("name")] = (i, m)
    return found


def find_section9_rows(scad_lines: list[str]) -> list[tuple[int, str, list[str]]]:
    """Return [(line_index, m_id, [param_names_on_that_row]), ...] for
    section 9's table, i.e. every commented row of the form
    '//  M-03  esp_hole_dx / esp_hole_dy / esp_hole_d  33/25/3.2'."""
    out = []
    in_section9 = False
    seen_row = False
    for i, line in enumerate(scad_lines):
        if "===  ASSUMED" in line and "THE OWNER'S LIST" in line:
            in_section9 = True
            continue
        if not in_section9:
            continue
        # The banner's OWN "// ---" underline (right after "9. === ...")
        # must not end the table before it starts — only a divider seen
        # AFTER at least one real row closes the table.
        if seen_row and line.strip().startswith("// -----"):
            break
        m = SECTION9_ROW_RE.match(line)
        if not m:
            continue
        row_id = m.group("mid")
        rest = m.group("rest")
        # Parameter names are the identifiers before two-or-more spaces
        # (the value column), stripped of stray "<-" annotations.
        head = re.split(r"\s{2,}", rest, maxsplit=1)[0]
        params = [tok for tok in re.split(r"\s*/\s*", head) if IDENT_RE.fullmatch(tok)]
        if params:
            seen_row = True
            out.append((i, row_id, params))
    return out


def build_patch(scad_path: Path, rows: list[Row], sheet_name: str, date: str):
    """Returns (new_lines, report_lines, matched_names, errors)."""
    text = scad_path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    assumed = find_assumed_params(lines)

    report: list[str] = []
    errors: list[str] = []
    matched_names: set[str] = set()
    skipped_rows: list[Row] = []
    unmatched_rows: list[Row] = []
    register_only = 0
    dup_targets: dict[str, list[Row]] = {}

    for row in rows:
        target = row.target()
        if not target:
            # Register-only (or, on a legacy sheet, a prose quantity that names
            # no parameter). Either way there is nothing to patch; it is not an
            # error, and it is not a match.
            register_only += 1
            continue
        # "could not — <why>" is the sitting's convention for an untakeable
        # measurement and belongs in the VALUE box. It is matched at the START
        # of `notes` only: several rows carry templated instruction text that
        # quotes the phrase ("if it is not, write 'could not — front end not
        # assembled'"), and a substring search silently skipped those rows.
        if (not row.value
                or row.value.lower().lstrip().startswith("could not")
                or row.notes.lower().lstrip().startswith("could not")):
            skipped_rows.append(row)
            continue
        dup_targets.setdefault(target, []).append(row)

    for quantity, candidate_rows in dup_targets.items():
        if quantity not in assumed:
            unmatched_rows.extend(candidate_rows)
            continue
        if len(candidate_rows) > 1:
            ids = ", ".join(r.id or f"line {r.lineno}" for r in candidate_rows)
            errors.append(
                f"CONFLICT: {len(candidate_rows)} rows target '{quantity}' ({ids}); "
                f"skipping all of them — resolve to one row per parameter and re-run."
            )
            continue
        row = candidate_rows[0]
        idx, m = assumed[quantity]
        old_value = m.group("value").strip()

        is_string_param = old_value.startswith('"')
        if is_string_param or row.unit.lower() == "enum":
            new_value_token = f'"{row.value.strip().strip(chr(34))}"'
        else:
            try:
                float(row.value)
            except ValueError:
                errors.append(
                    f"BAD VALUE: row {row.id or row.lineno} quantity='{quantity}' "
                    f"value='{row.value}' is not numeric and unit is not 'enum'; skipped."
                )
                continue
            new_value_token = row.value.strip()

        provenance = f"MEASURED({sheet_name}#{row.id or ('line ' + str(row.lineno))}, {date})"
        extras = []
        if row.tolerance:
            extras.append(f"tol {row.tolerance}")
        if row.photo_ref:
            extras.append(f"photo {row.photo_ref}")
        if row.notes:
            extras.append(row.notes)
        extra_txt = f" [{'; '.join(extras)}]" if extras else ""
        old_rest = m.group("rest")  # keeps the pre-existing rationale text, if any

        new_line = (
            f"{m.group('prefix')}{new_value_token}{m.group('mid')}"
            f"{provenance}{extra_txt}{old_rest}\n"
        )
        lines[idx] = new_line
        matched_names.add(quantity)
        report.append(
            f"  MATCH  {quantity:<20} {old_value!s:>10}  ->  {new_value_token:<10}  "
            f"(row {row.id or row.lineno})"
        )

    for row in unmatched_rows:
        tgt = row.target()
        report.append(
            f"  MISS   param='{tgt}' (row {row.id or row.lineno}) — "
            f"no live 'ASSUMED (see §9)' parameter named '{tgt}' in {scad_path.name}"
        )
        if row.has_param_col:
            # An explicitly named param that does not exist is an authoring
            # error in the sheet and must not pass silently. On a legacy sheet
            # every prose quantity misses, so a MISS there stays report-only
            # and the "nothing matched" check below is what fails the run.
            errors.append(
                f"row {row.id or row.lineno} names param '{tgt}', which is not a live "
                f"'ASSUMED (see §9)' parameter in {scad_path.name} — fix the sheet's param "
                f"column or the parameter's tag; nothing was applied for it."
            )
    for row in skipped_rows:
        why = "empty value" if not row.value else "marked 'could not' / no measurement taken"
        report.append(
            f"  SKIP   row {row.id or row.lineno} param='{row.target()}': {why}")
    if register_only:
        report.append(
            f"  REG    {register_only} register-only row(s) carry no param and were not "
            f"considered for patching (this is normal: stock dimensions, blocked rows, "
            f"and register/gate rows)")

    # DERIVED / ESTIMATED literals whose provenance names something we just
    # changed. These are hardcoded numbers that no assert re-derives, so a
    # patched input desynchronises them silently. Name them; never guess the
    # arithmetic.
    if matched_names:
        for i, line in enumerate(lines):
            m = DERIVED_RE.match(line)
            if not m or m.group("name") in matched_names:
                continue
            inputs = sorted({tok for tok in IDENT_RE.findall(m.group("basis"))
                             if tok in matched_names})
            if inputs:
                report.append(
                    f"  RECOMP {m.group('name')} (line {i + 1}) is "
                    f"{m.group('tag')}({m.group('basis')}) and is a hardcoded literal — "
                    f"{', '.join(inputs)} just changed. RECOMPUTE IT BY HAND in this commit; "
                    f"the tool will not guess the arithmetic."
                )

    # section 9 bookkeeping report (informational only — never edited).
    # find_section9_rows uses a plain "/"-split, which mis-tokenizes the
    # handful of §9 rows that use elliptical shorthand instead of full
    # names (e.g. "ko01_x_lo/x_hi/l_half/z_lo/z_hi" -> a bogus "x_hi"
    # fragment; "gcs_tx_*, ..." wildcard/comma rows aren't tokenized at
    # all). Rather than guess at the abbreviation, every extracted token
    # is checked against the file's REAL parameter names (either still
    # ASSUMED, or matched by this run) before being reported — a bogus
    # fragment that is neither is silently dropped, never reported as
    # "retired" or "still ASSUMED". This means shorthand/wildcard §9
    # rows (currently M-02, M-13, M-17) may be under-reported here;
    # check those by hand.
    known_params = set(assumed.keys()) | matched_names
    sec9 = find_section9_rows(lines)
    for _idx, row_id, raw_params in sec9:
        params = [p for p in raw_params if p in known_params]
        if not params:
            continue
        retired = [p for p in params if p in matched_names]
        still_assumed = [p for p in params if p not in matched_names and p in assumed]
        if retired and not still_assumed:
            report.append(f"  SEC9   {row_id}: fully retired ({', '.join(params)}) — strike this row by hand")
        elif retired:
            report.append(
                f"  SEC9   {row_id}: partially retired — {', '.join(retired)} now MEASURED, "
                f"{', '.join(still_assumed) or '(none)'} still ASSUMED"
            )

    return lines, report, matched_names, errors


def unified_diff(old_text: str, new_text: str, path_label: str) -> str:
    import difflib

    return "".join(
        difflib.unified_diff(
            old_text.splitlines(keepends=True),
            new_text.splitlines(keepends=True),
            fromfile=f"a/{path_label}",
            tofile=f"b/{path_label}",
        )
    )


def render_check(cad_dir: Path, openscad: str | None) -> tuple[bool, str]:
    import os

    cmd = ["./render.sh", "--stl"]
    env = None
    if openscad:
        env = {**os.environ, "OPENSCAD": openscad}
    proc = subprocess.run(
        cmd, cwd=str(cad_dir), capture_output=True, text=True, env=env
    )
    ok = proc.returncode == 0
    out = proc.stdout + proc.stderr
    return ok, out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sheet", required=True, type=Path, help="MEASUREMENT_RECORD_SHEET.csv")
    ap.add_argument(
        "--params",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "w17_params.scad",
        help="w17_params.scad to patch (default: ../w17_params.scad next to this tool)",
    )
    ap.add_argument("--apply", action="store_true", help="write the patch (default: dry run, diff only)")
    ap.add_argument("--skip-render", action="store_true", help="with --apply, skip the post-apply re-render")
    ap.add_argument("--openscad", default=None, help="OpenSCAD binary (passed through as OPENSCAD=...)")
    ap.add_argument("--date", default=None, help="override the MEASURED(...) date, default today (YYYY-MM-DD)")
    args = ap.parse_args(argv)

    date = args.date or _dt.date.today().isoformat()

    if not args.sheet.exists():
        print(f"error: sheet not found: {args.sheet}", file=sys.stderr)
        return 1
    try:
        rows = load_sheet(args.sheet)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if not args.params.exists():
        print(f"error: params file not found: {args.params}", file=sys.stderr)
        return 1

    old_text = args.params.read_text(encoding="utf-8")
    new_lines, report, matched, errors = build_patch(args.params, rows, args.sheet.name, date)
    new_text = "".join(new_lines)

    schema = "id,param,quantity,…" if (rows and rows[0].has_param_col) else "LEGACY (no 'param' column)"
    print(f"ingest_measurements.py — {args.sheet}  ->  {args.params}")
    print(f"  schema: {schema}")
    print(f"  {len(rows)} CSV row(s) read, {len(matched)} parameter(s) matched")
    print()
    for line in report:
        print(line)

    diff = unified_diff(old_text, new_text, args.params.name)
    print()
    if diff:
        print(diff)
    else:
        print("(no changes — nothing matched)")
        if rows and not matched:
            # The docstring has always promised exit 1 for "a matching problem".
            # A sheet that reads 254 rows and patches nothing IS the matching
            # problem the schema handshake is most likely to produce, and it used
            # to exit 0 — i.e. look like success.
            filled = [r for r in rows if r.target() and r.value]
            if not filled:
                errors.append(
                    f"{len(rows)} CSV row(s) read but not one row with a 'param' has a "
                    f"value — the sheet has not been filled in yet, or the values were "
                    f"written into the wrong column")
            else:
                errors.append(
                    f"{len(rows)} CSV row(s) read but no 'param'/'quantity' matched a live "
                    f"'ASSUMED (see §9)' parameter — check the sheet's column convention")

    if errors:
        print()
        for e in errors:
            print(f"  ERROR  {e}")
        return 1

    if not args.apply:
        print()
        print("dry run only — nothing written. Re-run with --apply to write the patch.")
        return 0

    if not matched:
        print()
        print("nothing matched — not writing (no-op apply refused).")
        return 0

    args.params.write_text(new_text, encoding="utf-8")
    print()
    print(f"applied: wrote {args.params}")

    if args.skip_render:
        print("--skip-render given: not re-rendering.")
        return 0

    cad_dir = args.params.parent
    ok, out = render_check(cad_dir, args.openscad)
    print()
    print("post-apply render (./render.sh --stl):")
    print(out)
    if ok:
        print("RENDER PASS — geometry still clean after the patch.")
        return 0
    else:
        print("RENDER FAIL — the patched file is still on disk (this is now a normal git diff); "
              "fix the offending value/assert before committing.")
        return 2


if __name__ == "__main__":
    sys.exit(main())
